# Copyright (c) 2022 The Aerospace Corporation
"""Walkthrough test for the ranging example.

This test file reproduces the calculations in examples/example.py to ensure the library's
core functionality (transforms, distances, visibility, and ENU basis) remains
correct and consistent.

Includes code generated by Gemini 2.0.
"""

import numpy as np
import pytest
from datetime import datetime
from gps_time import GPSTime

from gps_frames import (
    Position,
    distance,
    get_range_azimuth_elevation,
    get_east_north_up_basis,
    check_earth_obscuration,
)


def test_example_ranging_logic():
    """Reproduce and verify the ranging example logic."""
    # 1. SETUP: Time
    time = GPSTime.from_datetime(datetime(2017, 9, 2, 12, 0, 0))

    # 2. DEFINE LOCATIONS
    # Ground Antenna (LLA)
    ground_antenna_latitude_rad = np.radians(33.0)
    ground_antenna_longitude_rad = np.radians(-118.0)
    ground_antenna_altitude_m = 30.0

    ground_antenna_position = Position(
        np.array(
            [
                ground_antenna_latitude_rad,
                ground_antenna_longitude_rad,
                ground_antenna_altitude_m,
            ]
        ),
        time,
        "LLA",
    )

    # Satellite 1 (LEO - In View)
    satellite1_latitude_rad = np.radians(45.0)
    satellite1_longitude_rad = np.radians(-110.0)
    satellite1_altitude_m = 600e3

    satellite1_position = Position(
        np.array(
            [
                satellite1_latitude_rad,
                satellite1_longitude_rad,
                satellite1_altitude_m,
            ]
        ),
        time,
        "LLA",
    )

    # Satellite 2 (GEO - Not In View)
    satellite2_latitude_rad = np.radians(-10.0)
    satellite2_longitude_rad = np.radians(-30.0)
    satellite2_altitude_m = 30000e3

    satellite2_position = Position(
        np.array(
            [
                satellite2_latitude_rad,
                satellite2_longitude_rad,
                satellite2_altitude_m,
            ]
        ),
        time,
        "LLA",
    )

    # 3. VERIFY FRAME CONVERSIONS
    # Ensure ECEF and ECI coords are generated without error
    sat1_ecef = satellite1_position.get_position("ECEF")
    sat1_eci = satellite1_position.get_position("ECI")
    assert sat1_ecef.coordinates.shape == (3,)
    assert sat1_eci.coordinates.shape == (3,)

    # 4. VERIFY VISIBILITY (Line-of-Sight)
    ga_to_sat1_in_view = check_earth_obscuration(
        ground_antenna_position, satellite1_position, earth_adjustment_m=0.0
    )
    ga_to_sat2_in_view = check_earth_obscuration(
        ground_antenna_position, satellite2_position, earth_adjustment_m=0.0
    )
    sat1_to_sat2_in_view = check_earth_obscuration(
        satellite1_position, satellite2_position, earth_adjustment_m=0.0
    )

    assert ga_to_sat1_in_view == True, "Satellite 1 should be in view of ground antenna"
    assert ga_to_sat2_in_view == False, "Satellite 2 should NOT be in view of ground antenna"
    # Sat 2 is extremely high (GEO), so it should be visible from Sat 1 (LEO) 
    # unless blocked by the Earth's limb.
    assert sat1_to_sat2_in_view == True, "Satellite 2 should be in view of Satellite 1"

    # 5. VERIFY DISTANCE
    dist_ga_sat1 = distance(ground_antenna_position, satellite1_position)
    # Approx distance: sqrt( (600km)^2 + surface_arc^2 )
    # Just check it's a reasonable positive float
    assert isinstance(dist_ga_sat1, float)
    assert dist_ga_sat1 > 600e3

    # 6. VERIFY ENU ANGLES (Observer: Ground Antenna)
    enu_basis_ga = get_east_north_up_basis(ground_antenna_position)
    _, az1, el1 = get_range_azimuth_elevation(enu_basis_ga, satellite1_position)
    _, az2, el2 = get_range_azimuth_elevation(enu_basis_ga, satellite2_position)

    # Elevation for something in view should be > 0 (or > -0.1 default mask)
    assert el1 > 0, "Satellite 1 must have positive elevation"
    assert el2 < 0, "Satellite 2 must have negative elevation (below horizon)"

    # Check types
    assert isinstance(az1, float)
    assert isinstance(el1, float)


if __name__ == "__main__":
    pytest.main([__file__])
